#!/usr/bin/env python3
"""Spec lint for Dhanada v2 (SDD hygiene).

Checks, across specs/, rails/, .specify/:
  * every requirement id DH2-<AREA>-<nnn> is DEFINED exactly once (a line starting "- **DH2-...**");
  * every id REFERENCED (tasks, skills, companions, feature specs) is defined;
  * stale role names from superseded drafts do not appear in normative files;
  * open clarification markers ([NEEDS CLARIFICATION: ...], [NC-n], [verify]) are listed;
  * every tasks.md task row cites at least one requirement id;
  * writes specs/000-platform/traceability.md (requirement -> tasks that cite it).
Usage: spec_lint.py [repo_root]. Exit code 1 on any error-level finding. Stdlib only.
"""

from __future__ import annotations

import pathlib
import re
import sys

ID_RE = re.compile(r"DH2-[A-Z]{2,5}-\d{3}")
DEF_RE = re.compile(r"^- \*\*(DH2-[A-Z]{2,5}-\d{3})\*\*")
STALE_ROLES = [
    "Position Manager",
    "Strategist",
    "Desk Reviewer",
    "Compliance Auditor",
    "Desk Head",
    "Trader ",
    "Trader,",
    "Trader)",
    "Trader:",
    "Risk Office ",
    "Risk Office,",
    "Risk Office)",
]
STALE_EXEMPT = {"scenario-walkthrough.md"}  # records the earlier drafts it replaced
NC_RE = re.compile(r"\[NEEDS CLARIFICATION:[^\]]*\]|\[NC-\d+[^\]]*\]|\*\*\[verify\]\*\*|\[verify[^\]]*\]")


def expand(text: str) -> set[str]:
    """Ids in text, including ranges like DH2-CTL-001…005 and lists like DH2-PIPE-003/004/005."""
    out = set(ID_RE.findall(text))
    for m in re.finditer(r"(DH2-[A-Z]{2,5}-)(\d{3})((?:/\d{3})+)", text):
        for n in m.group(3).split("/")[1:]:
            out.add(m.group(1) + n)
    for m in re.finditer(r"(DH2-[A-Z]{2,5}-)(\d{3})[…-](\d{3})", text):
        a, b = int(m.group(2)), int(m.group(3))
        for k in range(a, b + 1):
            out.add(f"{m.group(1)}{k:03d}")
    return out


def main(argv: list[str]) -> int:
    root = pathlib.Path(argv[1]).resolve() if len(argv) > 1 else pathlib.Path(__file__).resolve().parents[1]
    spec_dir = root / "specs" / "000-platform"
    features = sorted(f for f in (root / "specs").glob("[0-9]*-*/*.md") if f.parent != spec_dir)
    normative = [
        *sorted(spec_dir.glob("*.md")),
        *features,
        root / ".specify/memory/constitution.md",
        *sorted((root / "rails").glob("*.md")),
    ]

    errors: list[str] = []
    warnings: list[str] = []
    defined: dict[str, list[str]] = {}
    all_refs: dict[str, set[str]] = {}

    for f in normative:
        text = f.read_text(encoding="utf-8")
        rel = f.relative_to(root).as_posix()
        for rid in expand(text):
            all_refs.setdefault(rid, set()).add(rel)
        for i, line in enumerate(text.splitlines(), 1):
            m = DEF_RE.match(line.strip())
            if m:
                defined.setdefault(m.group(1), []).append(f"{rel}:{i}")
            for nc in NC_RE.findall(line):
                if "Resolved" in line or "resolved" in line:
                    continue
                warnings.append(f"open clarification {rel}:{i}: {nc} — {line.strip()[:110]}")
            for s in STALE_ROLES if f.name not in STALE_EXEMPT else []:
                if (
                    s in line
                    and "superseded" not in line.lower()
                    and "replace" not in line.lower()
                    and "v2.0" not in line
                ):
                    errors.append(f"stale role '{s.strip()}' in {rel}:{i}: {line.strip()[:110]}")

    for rid, locs in defined.items():
        if len(locs) > 1:
            errors.append(f"duplicate definition {rid}: {', '.join(locs)}")
    for rid, files in sorted(all_refs.items()):
        if rid not in defined:
            errors.append(f"undefined requirement referenced: {rid} in {', '.join(sorted(files))}")

    # tasks must cite requirements; build traceability
    trace: dict[str, list[str]] = {rid: [] for rid in defined}
    for i, line in enumerate((spec_dir / "tasks.md").read_text(encoding="utf-8").splitlines(), 1):
        if re.match(r"^\| \d+\.\d+[a-z]? ", line):
            cells = [c.strip() for c in line.strip("|").split("|")]
            task_id, req_cell = cells[0].split(" ")[0], cells[2] if len(cells) > 2 else ""
            ids = expand(req_cell)
            if not ids and "DH2-" not in req_cell:
                errors.append(f"task {task_id} (tasks.md:{i}) cites no requirement id")
            for rid in ids:
                trace.setdefault(rid, []).append(task_id)
    uncovered = [rid for rid, t in trace.items() if not t and rid in defined]

    out = [
        "# Traceability — requirement → implementing tasks",
        "",
        "*Generated by `scripts/spec_lint.py`; do not edit by hand.*",
        "",
        "| Requirement | Defined in | Tasks |",
        "|---|---|---|",
    ]
    for rid in sorted(defined):
        out.append(f"| {rid} | {defined[rid][0]} | {', '.join(trace.get(rid, [])) or '— (uncovered)'} |")
    out += ["", f"Defined: {len(defined)} · Uncovered by any task: {len(uncovered)}"]
    (spec_dir / "traceability.md").write_text("\n".join(out) + "\n", encoding="utf-8")

    for e in errors:
        print("ERROR  ", e)
    for w in warnings:
        print("WARN   ", w)
    print(
        f"\n{len(defined)} requirements defined, {len(uncovered)} uncovered by tasks:",
        ", ".join(uncovered) if uncovered else "none",
    )
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
